---
plugin: amazon.aws.aws_ec2
regions:
  - us-west-2


compose:
  ansible_host: public_dns_name

hostnames:
  - name: tag:Name
    separator: ""
    prefix: ""

keyed_groups:
  - key: tags.Project
    prefix: "Project"
    separator: "_"
  - key: tags.Role
    prefix: "Server_Role"
    separator: "_"
  - key: tags.Group
    prefix: "Group"
    separator: "_"